FROM        node:8

WORKDIR     /usr/src/app

COPY        package*.json ./

RUN         npm install

COPY        . .

EXPOSE      8080


RUN         echo 'alias ll="ls -l"' >> ~/.bashrc

CMD         ["npm", "start"]