FROM        node:latest

WORKDIR     /home

COPY        . /home

RUN         apt-get update && \
            apt-get install -y python3 python3-pip && \
            apt-get install -y postfix

CMD         bash